# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Slurp-Remote
version:      0.3
version_from: lib/Tie/Function/Examples.pm
installdirs:  site
requires:
    File::Slurp:                   0
    File::Temp:                    0
    Sys::Hostname::FQDN:           0
    Tie::Hash:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
